name: MCMA_env
channels:
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=1.0=mkl
  - ca-certificates=2023.7.22=hbcca054_0
  - cudatoolkit=11.2.2=hc23eb0c_12
  - cudnn=8.1.0.77=h90431f1_0
  - icu=73.2=h59595ed_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=h166bdaf_0
  - libsqlite=3.43.0=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=16.0.6=h4dfa4b3_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.3=hd590300_0
  - pip=23.2.1=pyhd8ed1ab_0
  - python=3.8.18=h955ad1f_0
  - python_abi=3.8=2_cp38
  - readline=8.2=h8228510_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - sqlite=3.43.0=h2c6b66d_0
  - tbb=2021.10.0=h00ab1b0_1
  - tk=8.6.13=h2797004_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==0.15.0
      - astunparse==1.6.3
      - audioread==3.0.1
      - bidict==0.22.1
      - biosppy==2.1.2
      - cachetools==5.3.1
      - certifi==2020.4.5.1
      - cffi==1.16.0
      - chardet==3.0.4
      - charset-normalizer==3.2.0
      - clang==5.0
      - contourpy==1.1.1
      - cycler==0.10.0
      - decorator==5.1.1
      - ecg-plot==0.2.8
      - et-xmlfile==1.1.0
      - fastdtw==0.3.4
      - flatbuffers==1.12
      - fonttools==4.42.1
      - gast==0.4.0
      - google-auth==2.23.1
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.58.0
      - h5py==3.1.0
      - idna==2.9
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - joblib==1.3.2
      - keras==2.6.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - libclang==16.0.6
      - librosa==0.2.0
      - llvmlite==0.41.1
      - markdown==3.4.4
      - markupsafe==2.1.3
      - matplotlib==3.5.0
      - mne==0.20.5
      - msgpack==1.0.8
      - neurokit2==0.2.7
      - nose==1.3.7
      - numba==0.58.1
      - numpy==1.19.2
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - packaging==23.1
      - pandas==1.4.4
      - pillow==10.0.1
      - platformdirs==4.2.0
      - pooch==1.8.1
      - protobuf==3.19.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pyparsing==2.4.7
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.2
      - pyqtgraph==0.10.0
      - python-dateutil==2.8.1
      - pytz==2020.1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - requests==2.23.0
      - requests-oauthlib==1.3.1
      - resampy==0.4.3
      - rsa==4.9
      - scikit-learn==1.2.2
      - scipy==1.4.1
      - setuptools-scm==8.0.3
      - shortuuid==1.0.11
      - six==1.15.0
      - sklearn==0.0
      - soundfile==0.12.1
      - soxr==0.3.7
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-addons==0.21.0
      - tensorflow-estimator==2.10.0
      - tensorflow-gpu==2.6.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==1.1.0
      - threadpoolctl==2.1.0
      - tomli==2.0.1
      - tqdm==4.66.1
      - typeguard==2.13.3
      - typing-extensions==4.10.0
      - tzdata==2023.3
      - urllib3==1.25.9
      - werkzeug==2.3.7
      - wfdb==4.1.2
      - wrapt==1.12.1
      - xlrd==2.0.1
      - xlsxwriter==3.1.9
      - xlwt==1.3.0
      - zipp==3.17.0
